[package]
name = "tetris"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.3.0"

[dependencies.sdl2]
version = "0.38.0" # Use the desired version
default-features = false
features = ["image"] 
